import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import Link from "next/link";

export default function ReachPage() {
  return (
    <main style={{ background: "#080810", minHeight: "100vh" }}>
      <Nav />

      {/* HERO */}
      <section className="relative pt-40 pb-24 overflow-hidden">
        <div className="absolute inset-0 grid-bg opacity-30" />
        <div className="absolute top-0 right-0 w-[500px] h-[500px] rounded-full"
          style={{ background: "radial-gradient(ellipse, rgba(21,96,168,0.1) 0%, transparent 70%)" }} />
        <div className="relative max-w-6xl mx-auto px-6">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border text-xs font-medium mb-6"
            style={{ borderColor: "#252538", color: "#5BA3E0", background: "rgba(21,96,168,0.08)" }}>
            <span className="w-1.5 h-1.5 rounded-full bg-current" />
            OLTO Reach · Lead Generation
          </div>
          <h1 className="text-5xl md:text-6xl font-bold mb-6 leading-tight" style={{ color: "#EEEEF5" }}>
            Your pipeline.<br />
            <span className="gradient-text">Built while you sleep.</span>
          </h1>
          <p className="text-xl mb-10 max-w-xl" style={{ color: "#AAAABC" }}>
            OLTO Reach finds your ideal prospects, researches them, scores them, and fires outreach — automatically. You open your laptop to hot leads, not spreadsheets.
          </p>
          <Link href="/contact"
            className="inline-flex items-center gap-2 px-6 py-3.5 rounded-lg text-sm font-semibold text-white"
            style={{ background: "#1560A8" }}>
            Get Early Access
          </Link>
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section className="py-24 border-t" style={{ borderColor: "#252538", background: "#0F0F1A" }}>
        <div className="max-w-6xl mx-auto px-6">
          <p className="text-xs font-semibold uppercase tracking-widest mb-4 text-center" style={{ color: "#1560A8" }}>How it works</p>
          <h2 className="text-3xl font-bold text-center mb-16" style={{ color: "#EEEEF5" }}>
            From zero to outreach in four steps
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
            {[
              { step: "01", title: "Define your target", desc: "Tell us the sector, location, and size of business you want to reach. We handle the rest." },
              { step: "02", title: "AI researches prospects", desc: "We pull live data from Google, enrich with contact details, and score each prospect automatically." },
              { step: "03", title: "Outreach fires", desc: "Personalised emails are generated and sent at the right time. Hot leads are flagged for you." },
              { step: "04", title: "You close deals", desc: "Your dashboard shows every prospect, score, reply, and stage. You just show up to the interesting conversations." },
            ].map((item) => (
              <div key={item.step} className="p-6 rounded-xl border" style={{ background: "#161625", borderColor: "#252538" }}>
                <span className="text-2xl font-bold font-mono block mb-4" style={{ color: "#1560A8" }}>{item.step}</span>
                <h3 className="font-semibold mb-2" style={{ color: "#EEEEF5" }}>{item.title}</h3>
                <p className="text-sm leading-relaxed" style={{ color: "#888896" }}>{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FEATURES */}
      <section className="py-24">
        <div className="max-w-6xl mx-auto px-6">
          <h2 className="text-3xl font-bold mb-12" style={{ color: "#EEEEF5" }}>What's inside</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {[
              { title: "Live prospect research", desc: "Pulls real business data from Google Places. Every lead is fresh, not from a stale database." },
              { title: "AI lead scoring", desc: "Each prospect gets an automated score based on ratings, relevance, and enrichment. Hot leads jump to the top." },
              { title: "Email enrichment", desc: "We find and verify contact emails automatically. 30–50% hit rate without lifting a finger." },
              { title: "Automated outreach", desc: "Personalised emails generated by AI, sent via Gmail. You control the messaging, we handle the volume." },
              { title: "Pipeline dashboard", desc: "See every prospect, their status, score, and outreach history in one clean interface." },
              { title: "Built on your stack", desc: "Runs on n8n, Supabase, and Gmail. No vendor lock-in. You own the system." },
            ].map((item) => (
              <div key={item.title} className="flex gap-4 p-6 rounded-xl border card-hover" style={{ background: "#0F0F1A", borderColor: "#252538" }}>
                <div className="w-8 h-8 rounded flex items-center justify-center flex-shrink-0" style={{ background: "rgba(21,96,168,0.15)", color: "#1560A8" }}>✓</div>
                <div>
                  <h3 className="font-semibold mb-1" style={{ color: "#EEEEF5" }}>{item.title}</h3>
                  <p className="text-sm" style={{ color: "#888896" }}>{item.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 border-t" style={{ borderColor: "#252538", background: "#0F0F1A" }}>
        <div className="max-w-6xl mx-auto px-6 text-center">
          <h2 className="text-3xl font-bold mb-4" style={{ color: "#EEEEF5" }}>Want early access?</h2>
          <p className="mb-8" style={{ color: "#AAAABC" }}>OLTO Reach is currently in controlled rollout. Get in touch to discuss access.</p>
          <Link href="/contact"
            className="inline-flex items-center px-6 py-3.5 rounded-lg text-sm font-semibold text-white"
            style={{ background: "#1560A8" }}>
            Book a call
          </Link>
        </div>
      </section>

      <Footer />
    </main>
  );
}
